#%RAML 1.0
---

title: Iv Orchestration
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/individuals:
  /iv-orchestration:
    /iv-sessiondata:
      /search:
        post:
          displayName: Search for iv session data
          description: Given a credId and a journeyId, a search will be performed to retrieve the established iv session data.
          is: [headers.acceptHeader, headers.contentHeader]
          securedBy: [sec.x-application]
          body:
            application/json:
              type: !include schemas/submit-search-session-data.json
              example: !include examples/search-session-request-example.json
          responses:
            200:
             description: Includes an IvSessionData record that was searched for
             body:
              application/json:
               type: !include schemas/submit-search-session-data-response.json
               example: !include examples/search-session-response-example.json
